import type { StarletCard } from '../lib/cards.ts';
/**
 * Set 01 -- "Lunara: First Light".
 *
 * THIS FILE IS CONTENT. It holds card data and nothing else: no functions, no
 * conditionals, no imports beyond the type above. To add a card, drop the art
 * at public/cards/lun01/<number>.webp, append an object here, and run
 * `npm run content:check`. Nothing in lib/ needs to change.
 *
 * cardId is set plus number and never changes -- saves point at these strings.
 * Renumbering a card means giving it a new cardId, not editing an existing one.
 * Art: 5:7 portrait, 1024x1434, WebP, 250 KB max, full-bleed (the frame is UI).
 * See docs/CONTENT-GUIDE.md.
 */
export const SET_01: StarletCard[] = [
  {
    cardId: 'LUN-01-001',
    setId: 'LUN-01',
    number: 1,
    numberMax: 28,
    speciesId: 'mossbun',
    name: 'Mossbun',
    rarity: 'common',
    finish: 'matte',
    role: 'base',
    art: '/cards/lun01/001.webp',
    core: 'grove',
    zone: 'Moon Garden',
    illustrator: 'TBD',
    version: 1,
    isBase: true,
  },
  {
    cardId: 'LUN-01-002',
    setId: 'LUN-01',
    number: 2,
    numberMax: 28,
    speciesId: 'mossbun',
    name: 'Mossbun',
    subtitle: 'Garden Drift',
    rarity: 'common',
    finish: 'matte',
    role: 'pose',
    art: '/cards/lun01/002.webp',
    core: 'grove',
    zone: 'Moon Garden',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-003',
    setId: 'LUN-01',
    number: 3,
    numberMax: 28,
    speciesId: 'mossbun',
    name: 'Mossbun',
    subtitle: 'Moss Light',
    rarity: 'uncommon',
    finish: 'foil',
    role: 'foil',
    art: '/cards/lun01/003.webp',
    core: 'grove',
    zone: 'Moon Garden',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-004',
    setId: 'LUN-01',
    number: 4,
    numberMax: 28,
    speciesId: 'mossbun',
    name: 'Mossbun',
    subtitle: 'The Listening Field',
    rarity: 'rare',
    finish: 'fullart',
    role: 'fullart',
    art: '/cards/lun01/004.webp',
    core: 'grove',
    zone: 'Moon Garden',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-005',
    setId: 'LUN-01',
    number: 5,
    numberMax: 28,
    speciesId: 'emberpanda',
    name: 'Emberpanda',
    rarity: 'common',
    finish: 'matte',
    role: 'base',
    art: '/cards/lun01/005.webp',
    core: 'flare',
    zone: 'Prism Caves',
    illustrator: 'TBD',
    version: 1,
    isBase: true,
  },
  {
    cardId: 'LUN-01-006',
    setId: 'LUN-01',
    number: 6,
    numberMax: 28,
    speciesId: 'emberpanda',
    name: 'Emberpanda',
    subtitle: 'Banked Coals',
    rarity: 'uncommon',
    finish: 'matte',
    role: 'pose',
    art: '/cards/lun01/006.webp',
    core: 'flare',
    zone: 'Prism Caves',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-007',
    setId: 'LUN-01',
    number: 7,
    numberMax: 28,
    speciesId: 'emberpanda',
    name: 'Emberpanda',
    subtitle: 'Emberglow',
    rarity: 'rare',
    finish: 'foil',
    role: 'foil',
    art: '/cards/lun01/007.webp',
    core: 'flare',
    zone: 'Prism Caves',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-008',
    setId: 'LUN-01',
    number: 8,
    numberMax: 28,
    speciesId: 'emberpanda',
    name: 'Emberpanda',
    subtitle: 'Nightwatch',
    rarity: 'secret',
    finish: 'secret',
    role: 'secret',
    art: '/cards/lun01/008.webp',
    core: 'flare',
    zone: 'Prism Caves',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-009',
    setId: 'LUN-01',
    number: 9,
    numberMax: 28,
    speciesId: 'novafox',
    name: 'Novafox',
    rarity: 'rare',
    finish: 'matte',
    role: 'base',
    art: '/cards/lun01/009.webp',
    core: 'tide',
    zone: 'Crater Coast',
    illustrator: 'TBD',
    version: 1,
    isBase: true,
  },
  {
    cardId: 'LUN-01-010',
    setId: 'LUN-01',
    number: 10,
    numberMax: 28,
    speciesId: 'novafox',
    name: 'Novafox',
    subtitle: 'Tideline Sprint',
    rarity: 'rare',
    finish: 'matte',
    role: 'pose',
    art: '/cards/lun01/010.webp',
    core: 'tide',
    zone: 'Crater Coast',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-011',
    setId: 'LUN-01',
    number: 11,
    numberMax: 28,
    speciesId: 'novafox',
    name: 'Novafox',
    subtitle: 'Comet Trail',
    rarity: 'legendary',
    finish: 'foil',
    role: 'foil',
    art: '/cards/lun01/011.webp',
    core: 'tide',
    zone: 'Crater Coast',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-012',
    setId: 'LUN-01',
    number: 12,
    numberMax: 28,
    speciesId: 'dewlark',
    name: 'Dewlark',
    rarity: 'common',
    finish: 'matte',
    role: 'base',
    art: '/cards/lun01/012.webp',
    core: 'grove',
    zone: 'Moon Garden',
    illustrator: 'TBD',
    version: 1,
    isBase: true,
  },
  {
    cardId: 'LUN-01-013',
    setId: 'LUN-01',
    number: 13,
    numberMax: 28,
    speciesId: 'dewlark',
    name: 'Dewlark',
    subtitle: 'Morning Chorus',
    rarity: 'common',
    finish: 'matte',
    role: 'pose',
    art: '/cards/lun01/013.webp',
    core: 'grove',
    zone: 'Moon Garden',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-014',
    setId: 'LUN-01',
    number: 14,
    numberMax: 28,
    speciesId: 'dewlark',
    name: 'Dewlark',
    subtitle: 'Dewfall',
    rarity: 'uncommon',
    finish: 'foil',
    role: 'foil',
    art: '/cards/lun01/014.webp',
    core: 'grove',
    zone: 'Moon Garden',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-015',
    setId: 'LUN-01',
    number: 15,
    numberMax: 28,
    speciesId: 'dewlark',
    name: 'Dewlark',
    subtitle: 'The Quiet Meadow',
    rarity: 'rare',
    finish: 'fullart',
    role: 'fullart',
    art: '/cards/lun01/015.webp',
    core: 'grove',
    zone: 'Moon Garden',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-016',
    setId: 'LUN-01',
    number: 16,
    numberMax: 28,
    speciesId: 'shellune',
    name: 'Shellune',
    rarity: 'uncommon',
    finish: 'matte',
    role: 'base',
    art: '/cards/lun01/016.webp',
    core: 'tide',
    zone: 'Crater Coast',
    illustrator: 'TBD',
    version: 1,
    isBase: true,
  },
  {
    cardId: 'LUN-01-017',
    setId: 'LUN-01',
    number: 17,
    numberMax: 28,
    speciesId: 'shellune',
    name: 'Shellune',
    subtitle: 'Low Tide',
    rarity: 'uncommon',
    finish: 'matte',
    role: 'pose',
    art: '/cards/lun01/017.webp',
    core: 'tide',
    zone: 'Crater Coast',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-018',
    setId: 'LUN-01',
    number: 18,
    numberMax: 28,
    speciesId: 'shellune',
    name: 'Shellune',
    subtitle: 'Pearl Current',
    rarity: 'rare',
    finish: 'foil',
    role: 'foil',
    art: '/cards/lun01/018.webp',
    core: 'tide',
    zone: 'Crater Coast',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-019',
    setId: 'LUN-01',
    number: 19,
    numberMax: 28,
    speciesId: 'cindermoth',
    name: 'Cindermoth',
    rarity: 'uncommon',
    finish: 'matte',
    role: 'base',
    art: '/cards/lun01/019.webp',
    core: 'flare',
    zone: 'Prism Caves',
    illustrator: 'TBD',
    version: 1,
    isBase: true,
  },
  {
    cardId: 'LUN-01-020',
    setId: 'LUN-01',
    number: 20,
    numberMax: 28,
    speciesId: 'cindermoth',
    name: 'Cindermoth',
    subtitle: 'Ash Bloom',
    rarity: 'rare',
    finish: 'matte',
    role: 'pose',
    art: '/cards/lun01/020.webp',
    core: 'flare',
    zone: 'Prism Caves',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-021',
    setId: 'LUN-01',
    number: 21,
    numberMax: 28,
    speciesId: 'cindermoth',
    name: 'Cindermoth',
    subtitle: 'Emberwing',
    rarity: 'rare',
    finish: 'foil',
    role: 'foil',
    art: '/cards/lun01/021.webp',
    core: 'flare',
    zone: 'Prism Caves',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-022',
    setId: 'LUN-01',
    number: 22,
    numberMax: 28,
    speciesId: 'glimmerelk',
    name: 'Glimmerelk',
    rarity: 'rare',
    finish: 'matte',
    role: 'base',
    art: '/cards/lun01/022.webp',
    core: 'grove',
    zone: 'Moon Garden',
    illustrator: 'TBD',
    version: 1,
    isBase: true,
  },
  {
    cardId: 'LUN-01-023',
    setId: 'LUN-01',
    number: 23,
    numberMax: 28,
    speciesId: 'glimmerelk',
    name: 'Glimmerelk',
    subtitle: 'Antler Dawn',
    rarity: 'legendary',
    finish: 'foil',
    role: 'foil',
    art: '/cards/lun01/023.webp',
    core: 'grove',
    zone: 'Moon Garden',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-024',
    setId: 'LUN-01',
    number: 24,
    numberMax: 28,
    speciesId: 'glimmerelk',
    name: 'Glimmerelk',
    subtitle: 'First Contact',
    rarity: 'secret',
    finish: 'secret',
    role: 'secret',
    art: '/cards/lun01/024.webp',
    core: 'grove',
    zone: 'Moon Garden',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-025',
    setId: 'LUN-01',
    number: 25,
    numberMax: 28,
    speciesId: 'selenith',
    name: 'Selenith',
    rarity: 'legendary',
    finish: 'matte',
    role: 'base',
    art: '/cards/lun01/025.webp',
    core: 'tide',
    zone: 'Crater Coast',
    illustrator: 'TBD',
    version: 1,
    isBase: true,
  },
  {
    cardId: 'LUN-01-026',
    setId: 'LUN-01',
    number: 26,
    numberMax: 28,
    speciesId: 'selenith',
    name: 'Selenith',
    subtitle: 'Moonrise',
    rarity: 'legendary',
    finish: 'matte',
    role: 'pose',
    art: '/cards/lun01/026.webp',
    core: 'tide',
    zone: 'Crater Coast',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-027',
    setId: 'LUN-01',
    number: 27,
    numberMax: 28,
    speciesId: 'selenith',
    name: 'Selenith',
    subtitle: 'Crown of Lunara',
    rarity: 'legendary',
    finish: 'fullart',
    role: 'fullart',
    art: '/cards/lun01/027.webp',
    core: 'tide',
    zone: 'Crater Coast',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
  {
    cardId: 'LUN-01-028',
    setId: 'LUN-01',
    number: 28,
    numberMax: 28,
    speciesId: 'selenith',
    name: 'Selenith',
    subtitle: 'Night Slab',
    rarity: 'secret',
    finish: 'secret',
    role: 'secret',
    art: '/cards/lun01/028.webp',
    core: 'tide',
    zone: 'Crater Coast',
    illustrator: 'TBD',
    version: 1,
    isBase: false,
  },
];
